version: '3.1'

services:
  drupal:
    container_name: "dbusinesstest_drupal"
    build:
      context: ./docker
      dockerfile: Dockerfile-drupal
    ports:
      - 8888:80
    volumes:
      - "./docroot/modules:/var/www/html/modules"
      - "./docroot/profiles:/var/www/html/profiles"
      - "./docroot/themes:/var/www/html/themes"
      - "./docroot/sites:/var/www/html/sites"
    restart: always