version: '3.1'

services:
  drupal:
    container_name: "dbusinesstest_drupal"
    build:
      context: ./docker
      dockerfile: Dockerfile-drupal
    ports:
      - 8888:80
    volumes:
      - "./docroot/modules:/var/www/html/modules"
      - "./docroot/profiles:/var/www/html/profiles"
      - "./docroot/themes:/var/www/html/themes"
      - "./docroot/config:/var/www/html/config"
    restart: always
  mysql:
    image: mysql
    container_name: "dbusinesstest_mysql"
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    restart: always