FROM 'drupal:8-apache'

WORKDIR /var/www/html

COPY settings.php /var/www/html/sites/default/settings.php
COPY settings.local.php /var/www/html/sites/default/settings.local.php

# Install packages
RUN rm /bin/sh && ln -s /bin/bash /bin/sh && \
    apt-get update && apt-get install --no-install-recommends -y \
    curl \
    vim \
    wget \
    git \
    unzip \
    mysql-client

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
    ln -s /root/.composer/vendor/bin/drush /usr/local/bin/drush

# Install Drush
RUN composer global -n require drush/drush && \
    composer global -n update